"""schema, constraints and append-only triggers

Revision ID: c43f7713f25a
Revises:
Create Date: 2026-10-07 14:08:12.930270

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c43f7713f25a"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("dispute_id", sa.String(length=100), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("prompt_version", sa.String(length=50), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("plan", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True),
        sa.Column("cache_hit", sa.Boolean(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_runs")),
    )
    op.create_index(op.f("ix_agent_runs_dispute_id"), "agent_runs", ["dispute_id"], unique=False)
    op.create_table(
        "charters",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.String(length=100), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "config", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_charters")),
        sa.UniqueConstraint("merchant_id", "version", name="uq_charters_merchant_version"),
    )
    op.create_index(op.f("ix_charters_merchant_id"), "charters", ["merchant_id"], unique=False)
    op.create_table(
        "decisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("dispute_id", sa.String(length=100), nullable=False),
        sa.Column("action_type", sa.String(length=50), nullable=False),
        sa.Column(
            "action_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("verdict", sa.String(length=50), nullable=False),
        sa.Column("rule_id", sa.String(length=50), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "also_triggered",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("action_hash", sa.String(length=64), nullable=False),
        sa.Column("dispute_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("charter_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "action_type IN ('PROVIDE_EVIDENCE', 'SEND_MESSAGE', 'MAKE_OFFER', 'ACCEPT_CLAIM', 'ESCALATE', 'APPEAL')",
            name=op.f("ck_decisions_ck_action_type_actiontype"),
        ),
        sa.CheckConstraint(
            "verdict IN ('ALLOW', 'NEEDS_APPROVAL', 'DENY')", name=op.f("ck_decisions_ck_verdict_verdict")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_decisions")),
    )
    op.create_index(op.f("ix_decisions_dispute_id"), "decisions", ["dispute_id"], unique=False)
    op.create_table(
        "demo_sessions",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "metadata_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_demo_sessions")),
    )
    op.create_table(
        "disputes",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("state_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("reason", sa.String(length=100), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("seller_response_due_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "snapshot", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("demo_session_id", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "reason IN ('MERCHANDISE_OR_SERVICE_NOT_RECEIVED', 'MERCHANDISE_OR_SERVICE_NOT_AS_DESCRIBED', 'UNAUTHORISED', 'CREDIT_NOT_PROCESSED', 'DUPLICATE_TRANSACTION', 'INCORRECT_AMOUNT', 'PAYMENT_BY_OTHER_MEANS', 'CANCELED_RECURRING_BILLING', 'PROBLEM_WITH_REMITTANCE', 'OTHER')",  # noqa: E501
            name=op.f("ck_disputes_ck_reason_disputereason"),
        ),
        sa.CheckConstraint(
            "status IN ('WAITING_FOR_SELLER_RESPONSE', 'WAITING_FOR_BUYER_RESPONSE', 'UNDER_REVIEW', 'RESOLVED', 'OPEN', 'OTHER')",  # noqa: E501
            name=op.f("ck_disputes_ck_status_disputestatus"),
        ),
        sa.CheckConstraint(
            "amount = round(amount, 2) AND amount >= 0", name=op.f("ck_disputes_ck_disputes_amount_two_decimals")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_disputes")),
    )
    op.create_index(op.f("ix_disputes_demo_session_id"), "disputes", ["demo_session_id"], unique=False)
    op.create_table(
        "evidence_files",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("dispute_id", sa.String(length=100), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("file_type", sa.String(length=100), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("file_hash", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_files")),
    )
    op.create_index(op.f("ix_evidence_files_dispute_id"), "evidence_files", ["dispute_id"], unique=False)
    op.create_table(
        "jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("dispute_id", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column(
            "payload", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("run_after", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "kind IN ('sync_dispute', 'run_agent', 'execute_decision', 'reconcile', 'expire_approvals')",
            name=op.f("ck_jobs_ck_kind_jobkind"),
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'DEAD_LETTER')",
            name=op.f("ck_jobs_ck_status_jobstatus"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    op.create_index(op.f("ix_jobs_dispute_id"), "jobs", ["dispute_id"], unique=False)
    op.create_index(
        "uq_jobs_pending_dispute_kind",
        "jobs",
        ["dispute_id", "kind"],
        unique=True,
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.create_table(
        "ledger_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("dispute_id", sa.String(length=100), nullable=False),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("event_kind", sa.String(length=50), nullable=False),
        sa.Column(
            "payload", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("recorded_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "event_kind IN ('WEBHOOK_RECEIVED', 'DISPUTE_SYNCED', 'RUN_STARTED', 'EVIDENCE_BUILT', 'PLAN_PROPOSED', 'GATE_DECIDED', 'APPROVAL_REQUESTED', 'APPROVAL_RESOLVED', 'EXECUTION_INTENDED', 'EXECUTION_SENT', 'EXECUTION_CONFIRMED', 'EXECUTION_FAILED', 'INJECTION_FLAGGED', 'NO_ACTION', 'RUN_FAILED')",  # noqa: E501
            name=op.f("ck_ledger_events_ck_event_kind_timelineeventkind"),
        ),
        sa.CheckConstraint(
            "sequence_number >= 1",
            name=op.f("ck_ledger_events_ck_ledger_events_seq_positive"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ledger_events")),
        sa.UniqueConstraint("dispute_id", "sequence_number", name="uq_ledger_events_dispute_seq"),
    )
    op.create_index(op.f("ix_ledger_events_dispute_id"), "ledger_events", ["dispute_id"], unique=False)
    op.create_table(
        "orders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_code", sa.String(length=30), nullable=False),
        sa.Column("merchant_id", sa.String(length=100), nullable=False),
        sa.Column("customer_email", sa.String(length=255), nullable=False),
        sa.Column("paypal_transaction_id", sa.String(length=100), nullable=True),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column(
            "items", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("demo_session_id", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('PENDING', 'PAID', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'DISPUTED')",
            name=op.f("ck_orders_ck_status_orderstatus"),
        ),
        sa.CheckConstraint(
            "amount = round(amount, 2) AND amount >= 0", name=op.f("ck_orders_ck_orders_amount_two_decimals")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
    )
    op.create_index(op.f("ix_orders_demo_session_id"), "orders", ["demo_session_id"], unique=False)
    op.create_index(op.f("ix_orders_merchant_id"), "orders", ["merchant_id"], unique=False)
    op.create_index(op.f("ix_orders_order_code"), "orders", ["order_code"], unique=True)
    op.create_index(op.f("ix_orders_paypal_transaction_id"), "orders", ["paypal_transaction_id"], unique=False)
    op.create_table(
        "webhook_events",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("transmission_id", sa.String(length=100), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("resource_type", sa.String(length=100), nullable=True),
        sa.Column(
            "raw_payload", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook_events")),
    )
    op.create_index(op.f("ix_webhook_events_event_type"), "webhook_events", ["event_type"], unique=False)
    op.create_index(op.f("ix_webhook_events_transmission_id"), "webhook_events", ["transmission_id"], unique=True)
    op.create_table(
        "approvals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("decision_id", sa.Uuid(), nullable=False),
        sa.Column("dispute_id", sa.String(length=100), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolution", sa.String(length=50), nullable=False),
        sa.Column(
            "edited_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "resolution IN ('PENDING', 'APPROVE', 'DENY', 'EDIT', 'EXPIRED')",
            name=op.f("ck_approvals_ck_resolution_approvalresolution"),
        ),
        sa.ForeignKeyConstraint(["decision_id"], ["decisions.id"], name=op.f("fk_approvals_decision_id_decisions")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approvals")),
    )
    op.create_index(op.f("ix_approvals_decision_id"), "approvals", ["decision_id"], unique=False)
    op.create_index(op.f("ix_approvals_dispute_id"), "approvals", ["dispute_id"], unique=False)
    op.create_index(op.f("ix_approvals_token_hash"), "approvals", ["token_hash"], unique=True)
    op.create_table(
        "executions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("decision_id", sa.Uuid(), nullable=False),
        sa.Column("dispute_id", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("paypal_debug_id", sa.String(length=100), nullable=True),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column(
            "confirmed_snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('INTENDED', 'SENT', 'CONFIRMED', 'FAILED')",
            name=op.f("ck_executions_ck_status_executionstatus"),
        ),
        sa.ForeignKeyConstraint(["decision_id"], ["decisions.id"], name=op.f("fk_executions_decision_id_decisions")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_executions")),
        sa.UniqueConstraint("decision_id", name=op.f("uq_executions_decision_id")),
    )
    op.create_index(op.f("ix_executions_dispute_id"), "executions", ["dispute_id"], unique=False)
    op.create_table(
        "tracking_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=True),
        sa.Column("carrier", sa.String(length=100), nullable=False),
        sa.Column("tracking_number", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("event_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "payload", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('PRE_TRANSIT', 'IN_TRANSIT', 'OUT_FOR_DELIVERY', 'DELIVERED', 'RETURNED', 'EXCEPTION')",
            name=op.f("ck_tracking_events_ck_status_trackingstatus"),
        ),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], name=op.f("fk_tracking_events_order_id_orders")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tracking_events")),
    )
    op.create_index(op.f("ix_tracking_events_order_id"), "tracking_events", ["order_id"], unique=False)
    op.create_index(op.f("ix_tracking_events_tracking_number"), "tracking_events", ["tracking_number"], unique=False)
    # ### end Alembic commands ###

    # Note: A database owner or superuser could drop the trigger;
    # this is accepted for demo environments per step 03 specification.
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("""
            CREATE OR REPLACE FUNCTION reject_append_only_mutation()
            RETURNS TRIGGER AS $$
            BEGIN
                RAISE EXCEPTION 'Table % is append-only: UPDATE and DELETE operations are prohibited', TG_TABLE_NAME;
            END;
            $$ LANGUAGE plpgsql;
        """)
        op.execute("""
            DROP TRIGGER IF EXISTS reject_decisions_mutation ON decisions;
            CREATE TRIGGER reject_decisions_mutation
            BEFORE UPDATE OR DELETE ON decisions
            FOR EACH ROW
            EXECUTE FUNCTION reject_append_only_mutation();
        """)
        op.execute("""
            DROP TRIGGER IF EXISTS reject_ledger_events_mutation ON ledger_events;
            CREATE TRIGGER reject_ledger_events_mutation
            BEFORE UPDATE OR DELETE ON ledger_events
            FOR EACH ROW
            EXECUTE FUNCTION reject_append_only_mutation();
        """)


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("DROP TRIGGER IF EXISTS reject_decisions_mutation ON decisions;")
        op.execute("DROP TRIGGER IF EXISTS reject_ledger_events_mutation ON ledger_events;")
        op.execute("DROP FUNCTION IF EXISTS reject_append_only_mutation();")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tracking_events_tracking_number"), table_name="tracking_events")
    op.drop_index(op.f("ix_tracking_events_order_id"), table_name="tracking_events")
    op.drop_table("tracking_events")
    op.drop_index(op.f("ix_executions_dispute_id"), table_name="executions")
    op.drop_table("executions")
    op.drop_index(op.f("ix_approvals_token_hash"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_dispute_id"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_decision_id"), table_name="approvals")
    op.drop_table("approvals")
    op.drop_index(op.f("ix_webhook_events_transmission_id"), table_name="webhook_events")
    op.drop_index(op.f("ix_webhook_events_event_type"), table_name="webhook_events")
    op.drop_table("webhook_events")
    op.drop_index(op.f("ix_orders_paypal_transaction_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_order_code"), table_name="orders")
    op.drop_index(op.f("ix_orders_merchant_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_demo_session_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_ledger_events_dispute_id"), table_name="ledger_events")
    op.drop_table("ledger_events")
    op.drop_index("uq_jobs_pending_dispute_kind", table_name="jobs", postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_index(op.f("ix_jobs_dispute_id"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_evidence_files_dispute_id"), table_name="evidence_files")
    op.drop_table("evidence_files")
    op.drop_index(op.f("ix_disputes_demo_session_id"), table_name="disputes")
    op.drop_table("disputes")
    op.drop_table("demo_sessions")
    op.drop_index(op.f("ix_decisions_dispute_id"), table_name="decisions")
    op.drop_table("decisions")
    op.drop_index(op.f("ix_charters_merchant_id"), table_name="charters")
    op.drop_table("charters")
    op.drop_index(op.f("ix_agent_runs_dispute_id"), table_name="agent_runs")
    op.drop_table("agent_runs")
    # ### end Alembic commands ###
